// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1-devel
// 	protoc        v5.26.1
// source: extend/stag/stag.proto

package stag

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NamingCase int32

const (
	NamingCase_CamelCase  NamingCase = 0
	NamingCase_PascalCase NamingCase = 1
	NamingCase_SnakeCase  NamingCase = 2
)

// Enum value maps for NamingCase.
var (
	NamingCase_name = map[int32]string{
		0: "CamelCase",
		1: "PascalCase",
		2: "SnakeCase",
	}
	NamingCase_value = map[string]int32{
		"CamelCase":  0,
		"PascalCase": 1,
		"SnakeCase":  2,
	}
)

func (x NamingCase) Enum() *NamingCase {
	p := new(NamingCase)
	*p = x
	return p
}

func (x NamingCase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NamingCase) Descriptor() protoreflect.EnumDescriptor {
	return file_extend_stag_stag_proto_enumTypes[0].Descriptor()
}

func (NamingCase) Type() protoreflect.EnumType {
	return &file_extend_stag_stag_proto_enumTypes[0]
}

func (x NamingCase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NamingCase.Descriptor instead.
func (NamingCase) EnumDescriptor() ([]byte, []int) {
	return file_extend_stag_stag_proto_rawDescGZIP(), []int{0}
}

type Tag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Case NamingCase `protobuf:"varint,1,opt,name=case,proto3,enum=stag.NamingCase" json:"case,omitempty"`
	Name string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Omitempty bool       `protobuf:"varint,3,opt,name=omitempty,proto3" json:"omitempty,omitempty"`
}

func (x *Tag) Reset() {
	*x = Tag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extend_stag_stag_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_extend_stag_stag_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_extend_stag_stag_proto_rawDescGZIP(), []int{0}
}

func (x *Tag) GetCase() NamingCase {
	if x != nil {
		return x.Case
	}
	return NamingCase_CamelCase
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetOmitempty() bool {
	if x != nil {
		return x.Omitempty
	}
	return false
}

var file_extend_stag_stag_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: ([]*Tag)(nil),
		Field:         50000,
		Name:          "stag.struct_tags",
		Tag:           "bytes,50000,rep,name=struct_tags",
		Filename:      "extend/stag/stag.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: ([]*Tag)(nil),
		Field:         50001,
		Name:          "stag.field_tags",
		Tag:           "bytes,50001,rep,name=field_tags",
		Filename:      "extend/stag/stag.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         50002,
		Name:          "stag.tags",
		Tag:           "bytes,50002,rep,name=tags",
		Filename:      "extend/stag/stag.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// repeated stag.Tag struct_tags = 50000;
	E_StructTags = &file_extend_stag_stag_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// repeated stag.Tag field_tags = 50001;
	E_FieldTags = &file_extend_stag_stag_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// repeated string tags = 50002;
	E_Tags = &file_extend_stag_stag_proto_extTypes[2]
)

var File_extend_stag_stag_proto protoreflect.FileDescriptor

var file_extend_stag_stag_proto_rawDesc = []byte{
	0x0a, 0x16, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x2f, 0x73, 0x74, 0x61, 0x67, 0x2f, 0x73, 0x74,
	0x61, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x73, 0x74, 0x61, 0x67, 0x1a, 0x20,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x5d, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x12, 0x24, 0x0a, 0x04, 0x63, 0x61, 0x73, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x73, 0x74, 0x61, 0x67, 0x2e, 0x4e, 0x61, 0x6d,
	0x69, 0x6e, 0x67, 0x43, 0x61, 0x73, 0x65, 0x52, 0x04, 0x63, 0x61, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x6d, 0x69, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x6f, 0x6d, 0x69, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2a,
	0x3a, 0x0a, 0x0a, 0x4e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x73, 0x65, 0x12, 0x0d, 0x0a,
	0x09, 0x43, 0x61, 0x6d, 0x65, 0x6c, 0x43, 0x61, 0x73, 0x65, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a,
	0x50, 0x61, 0x73, 0x63, 0x61, 0x6c, 0x43, 0x61, 0x73, 0x65, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09,
	0x53, 0x6e, 0x61, 0x6b, 0x65, 0x43, 0x61, 0x73, 0x65, 0x10, 0x02, 0x3a, 0x4a, 0x0a, 0x0b, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x5f, 0x74, 0x61, 0x67, 0x73, 0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x6c,
	0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd0, 0x86, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x73, 0x74, 0x61, 0x67, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x0a, 0x73, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x54, 0x61, 0x67, 0x73, 0x3a, 0x4b, 0x0a, 0x0a, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x5f, 0x74, 0x61, 0x67, 0x73, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd1, 0x86, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09,
	0x2e, 0x73, 0x74, 0x61, 0x67, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x54, 0x61, 0x67, 0x73, 0x3a, 0x33, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x1d, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd2, 0x86, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x78, 0x74,
	0x65, 0x6e, 0x64, 0x2f, 0x73, 0x74, 0x61, 0x67, 0x3b, 0x73, 0x74, 0x61, 0x67, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_extend_stag_stag_proto_rawDescOnce sync.Once
	file_extend_stag_stag_proto_rawDescData = file_extend_stag_stag_proto_rawDesc
)

func file_extend_stag_stag_proto_rawDescGZIP() []byte {
	file_extend_stag_stag_proto_rawDescOnce.Do(func() {
		file_extend_stag_stag_proto_rawDescData = protoimpl.X.CompressGZIP(file_extend_stag_stag_proto_rawDescData)
	})
	return file_extend_stag_stag_proto_rawDescData
}

var file_extend_stag_stag_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_extend_stag_stag_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_extend_stag_stag_proto_goTypes = []interface{}{
	(NamingCase)(0),                     // 0: stag.NamingCase
	(*Tag)(nil),                         // 1: stag.Tag
	(*descriptorpb.FileOptions)(nil),    // 2: google.protobuf.FileOptions
	(*descriptorpb.MessageOptions)(nil), // 3: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 4: google.protobuf.FieldOptions
}
var file_extend_stag_stag_proto_depIdxs = []int32{
	0, // 0: stag.Tag.case:type_name -> stag.NamingCase
	2, // 1: stag.struct_tags:extendee -> google.protobuf.FileOptions
	3, // 2: stag.field_tags:extendee -> google.protobuf.MessageOptions
	4, // 3: stag.tags:extendee -> google.protobuf.FieldOptions
	1, // 4: stag.struct_tags:type_name -> stag.Tag
	1, // 5: stag.field_tags:type_name -> stag.Tag
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	4, // [4:6] is the sub-list for extension type_name
	1, // [1:4] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_extend_stag_stag_proto_init() }
func file_extend_stag_stag_proto_init() {
	if File_extend_stag_stag_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_extend_stag_stag_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_extend_stag_stag_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_extend_stag_stag_proto_goTypes,
		DependencyIndexes: file_extend_stag_stag_proto_depIdxs,
		EnumInfos:         file_extend_stag_stag_proto_enumTypes,
		MessageInfos:      file_extend_stag_stag_proto_msgTypes,
		ExtensionInfos:    file_extend_stag_stag_proto_extTypes,
	}.Build()
	File_extend_stag_stag_proto = out.File
	file_extend_stag_stag_proto_rawDesc = nil
	file_extend_stag_stag_proto_goTypes = nil
	file_extend_stag_stag_proto_depIdxs = nil
}
